name: Rejectlist
options:
  bundleIdPrefix: com.shimondeitel.rejectlist
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Rejectlist:
    type: application
    platform: iOS
    sources:
      - path: Rejectlist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.rejectlist
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Rejectlist/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  RejectlistTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RejectlistTests
      - path: Rejectlist.storekit
    dependencies:
      - target: Rejectlist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.rejectlist.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  RejectlistUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: RejectlistUITests
    dependencies:
      - target: Rejectlist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.rejectlist.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Rejectlist:
    build:
      targets:
        Rejectlist: all
        RejectlistTests: [test]
        RejectlistUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Rejectlist.storekit
    test:
      config: Debug
      storeKitConfiguration: Rejectlist.storekit
      targets:
        - RejectlistTests
        - RejectlistUITests
    archive:
      config: Release
